In [1]:
import numpy as np

In [2]:
array = np.array([2,3,5,7,11,13,17,19,29,31])

In [3]:
array[0]

2

In [5]:
array[2]

5

In [6]:
array[-1]

31

In [7]:
array[-2]

29

In [8]:
array[[1,2,4]]

array([ 3,  5, 11])

In [9]:
array2 = np.array([2, 1, 3])

In [11]:
array[array2]

array([5, 3, 7])

In [12]:
array[2:7]

array([ 5,  7, 11, 13, 17])

In [13]:
array[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [15]:
array[2:]

array([ 5,  7, 11, 13, 17, 19, 29, 31])

In [16]:
array[2:11:2]

array([ 5, 11, 17, 29])

In [35]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [36]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
#이와 같은 상황들을 간단하게 만들기 위해 넘파이가 필요함

array3 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

result = []
for i in range(len(array3)):
    array3[i] = 2 * array3[i]
    result.append(array3[i])
    print(result)


[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [38]:
array1 = np.arange(10)
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [40]:
array1 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [41]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [43]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [44]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])