In [1]:
import numpy

In [6]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [7]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [8]:
type(array1)

numpy.ndarray

In [17]:
#1차원이라서 11, 만 나온 것
array1.shape

(11,)

In [12]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
type(array2)

numpy.ndarray

In [14]:
#2차원 배열
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#행이 3이고 열(가로)이 4인 배열
arrray2.shape

(3, 4)

In [18]:
array1.size

11

In [19]:
# 3*4라서 12가 나온 것
array2.size

12

In [20]:
array1 = numpy.full(6, 0)
print(array1)

[0 0 0 0 0 0]


In [22]:
array2 = numpy.zeros(6, dtype=int)
print(array2)

[0 0 0 0 0 0]


In [24]:
array3 = numpy.ones(6, dtype=int)
print(array3)

[1 1 1 1 1 1]


In [25]:
#numpy 모듈 안에 random모듈이 있고, 그 안에 random 함수가 있는 것
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
print(array1)
print()
print(array2)

[0.00438973 0.13434275 0.61643272 0.65865865 0.55745114 0.89884062]

[0.33073635 0.63532978 0.06020852 0.42086474 0.97738061 0.43007727]


In [26]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [27]:
array2 = numpy.arange(2, 7)
print(array2)

[2 3 4 5 6]


In [28]:
array3 = numpy.arange(3, 17, 3)
print(array3)

[ 3  6  9 12 15]
